# Generated by Django 2.1.7 on 2019-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canvas_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=100)),
                ('recurso', models.CharField(max_length=100)),
                ('proposta', models.CharField(max_length=100)),
                ('relacionamento', models.CharField(max_length=100)),
                ('canal', models.CharField(max_length=100)),
                ('segmento', models.CharField(max_length=100)),
                ('custo', models.CharField(max_length=100)),
                ('receita', models.CharField(max_length=100)),
            ],
        ),
    ]
