# Generated by Django 2.1.5 on 2019-03-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='canvas_model',
            new_name='CanvasModel',
        ),
    ]
