# Generated by Django 2.1.5 on 2019-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_auto_20190307_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasmodel',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='canal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='parceiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='proposta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='receita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='recurso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='relacionamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canvasmodel',
            name='segmento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
