# Generated by Django 2.1.5 on 2019-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_auto_20190310_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceiroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='canvasmodel',
            name='parceiro',
        ),
    ]
