# Generated by Django 2.1.5 on 2019-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_auto_20190310_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='canvasmodel',
            name='atividade',
        ),
    ]
