# Generated by Django 2.1.5 on 2019-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_auto_20190310_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionamentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CanvasModel',
        ),
    ]
