# Generated by Django 2.1.5 on 2019-03-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_auto_20190310_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelacionamentoModel',
            new_name='RelModel',
        ),
        migrations.AlterField(
            model_name='parceiromodel',
            name='parceiro',
            field=models.CharField(default=12032019, max_length=100),
            preserve_default=False,
        ),
    ]
